config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "events#index"

  resources :events do
    resources :event_attendings, only: [ :new, :create, :update ]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User", inverse_of: "created_events"
  has_many :event_attendings, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendings, source: :event_attendee

  # def self.past
  #   Event.where("event_date < :today", { today: Time.now })
  # end

  # def self.pending
  #   Event.where("event_date >= :today", { today: Time.now })
  # end
  #
  # Replaced class methods above with :scope

  scope :past_events, -> { where("event_date < ?", Time.now) }

  scope :pending_events, -> { where("event_date >= :today", today: Time.now) }

  enum :status, { publicized: 0, privatized: 1 }
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
  belongs_to :event_attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"

  enum :rsvp, { rejected: 0, accepted: 1, pending: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_events, class_name: "Event", foreign_key: "creator_id", inverse_of: "creator"
  has_many :event_attendings, foreign_key: :event_attendee_id
  has_many :attended_events, through: :event_attendings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/event_attendings_controller.rb
class EventAttendingsController < ApplicationController
  before_action :authenticate_user!

  def new
    @event_attending = EventAttending.new
  end

  def create
    @event = Event.find(params[:event_id])
    @invitee = User.find(params[:event_attending][:invitee_id])

    unless @event.attendees.include?(@invitee)
      @event.event_attendings.create event_attendee: @invitee
      flash[:notice] = "#{@invitee.email} has been invited"
      redirect_to event_path(params[:event_id])
    else
      flash[:error] = "#{@invitee.email} has already been invited"
      redirect_to event_path(params[:event_id])
    end
  end

  def update
    event_attending = EventAttending.find_by(event_attendee_id: current_user.id, attended_event_id: params[:event_id])

    if params[:response] == "0"
      event_attending.rejected!
    elsif params[:response] =="1"
      event_attending.accepted!
    end

    flash[:notice] = "You have #{event_attending.rsvp} the invitation"
    redirect_back fallback_location: root_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  def index
    # @past_events = Event.past
    # @pending_events = Event.pending
    # Replaced class methods above with :scope in model

    @past_events = Event.past_events
    @pending_events = Event.pending_events
  end

  def show
    # @event = Event.where(creator_id: event_params[:creator_id])
    @event = Event.find(params[:id])
    @attendings = EventAttending.where("attended_event_id = ? AND rsvp = ?", @event.id, 1)
  end

  def new
    @event = Event.new(status: :privatized)
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      flash[:notice] = "Event successfully created"
      redirect_to @event
    else
      flash.now[:error] = "Error creating an event. Please try again"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:notice] = "Event successfully updated"
      redirect_to @event
    else
      flash.now[:error] = "Couldn't update event. Try again"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])

    @event.destroy
    redirect_to root_path
  end


  private

  def event_params
    params.expect(event: [ :theme, :event_date, :venue, :description, :status ])
    # params.require(:event).permit(:theme, :event_date, :venue, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [ :show ]
  def show
    @created_events = current_user.created_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendings_helper.rb
module EventAttendingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendings/new.html.erb
<%= form_with model: @event_attending, url:  event_event_attendings_path do |f| %>
    <%= f.text_field :invitee_id%>
    <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<%= link_to events_path do%>
    <h1>PRIVATE EVENTS</h1>
<% end %>
<h2>Edit event</h2>
<%= form_with model: @event do |form| %>
    <div class="form-container">
        <div class="theme-wrapper">
            <%= form.label "theme"%><br>
            <%= form.text_field "theme" %>
        </div>
        <div class="venue-wrapper">
            <%= form.label "venue"%><br>
            <%= form.text_field "venue" %>
        </div>
        <div class="event-date-wrapper">
            <%= form.label "event_date"%><br>
            <%= form.datetime_select "event_date" %>
        </div>
        <div class="description-wrapper">
            <%= form.label "description"%><br>
            <%= form.text_area "description" %>
        </div>
        <div class="status-wrapper">
            <%= form.collection_radio_buttons :status, Event.statuses.keys, :to_s, :humanize %>
        </div>
        <%= form.submit %>
    </div>
<% end %>

app/views/events/index.html.erb
<%= link_to events_path do%>
    <h1>PRIVATE EVENTS</h1>
<% end %>
<p><%= link_to "User profile", user_path(current_user.id) %></p>
<div><%= link_to "Created events", user_path(current_user.id) %></div>
<h2>Past Events</h2>
<% @past_events.each do |event| %>
    <ul>
        <li><%= event.theme %></li>
        <li><%= event.event_date %></li>
        <li><%= event.venue %></li>
        <li><%= event.description %></li>
    </ul>
    <p><%= link_to "Show more", event_path(event.id) %></p>
<% end %>

<h2>Pending Events</h2>
<% @pending_events.each do |event| %>
    <% if event.publicized? || event.attendees.include?(current_user) %>
    <ul>
        <li><%= event.theme %></li>
        <li><%= event.event_date %></li>
        <li><%= event.venue %></li>
        <li><%= event.description %></li>
    </ul>
    <p><%= link_to "Show more", event_path(event.id) %></p>
    <% end %>
<% end %>

app/views/events/new.html.erb
<%= link_to events_path do%>
    <h1>PRIVATE EVENTS</h1>
<% end %>
<h2>Create event</h2>
<%= form_with model: @event do |form| %>
    <div class="form-container">
        <div class="theme-wrapper">
            <%= form.label "theme"%><br>
            <%= form.text_field "theme" %>
        </div>
        <div class="venue-wrapper">
            <%= form.label "venue"%><br>
            <%= form.text_field "venue" %>
        </div>
        <div class="event-date-wrapper">
            <%= form.label "event_date"%><br>
            <%= form.datetime_select "event_date" %>
        </div>
        <div class="description-wrapper">
            <%= form.label "description"%><br>
            <%= form.text_area "description" %>
        </div>
        <div class="status-wrapper">
            <%= form.collection_radio_buttons :status, Event.statuses.keys, :to_s, :humanize %>
        </div>
        <%= form.submit %>
    </div>
<% end %>

app/views/events/show.html.erb
<%= link_to events_path do%>
    <h1>PRIVATE EVENTS</h1>
<% end %>
<ul>
    <li><%= @event.theme %></li>
    <li><%= @event.event_date %></li>
    <li><%= @event.venue %></li>
    <li><%= @event.venue %></li>
    <li><%= @event.status %></li>
    <%= link_to "Edit event", edit_event_path(@event) if current_user == @event.creator%>
</ul>
<% unless @event.creator == current_user %>
<div><%= button_to "Attend event",  event_event_attending_path(@event, response: 1), method: :patch %>
<%= button_to "Decline invitation",  event_event_attending_path(@event, response: 0), method: :patch %></div>
<% end %>

<h2>Attendees</h2>
<% @attendings.each do |attendee| %>
    <p><%= User.find(attendee.event_attendee_id).email %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <p class="error"><%= flash.now[:error] %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<%= link_to events_path do%>
    <h1>PRIVATE EVENTS</h1>
<% end %>
<h2>Created Events</h2>
<div><%= link_to "Create an event", new_event_path %></div>
<% @created_events.each do |event| %>
    <ul>
        <li><%= event.theme %></li>
        <li><%= event.event_date %></li>
        <li><%= event.venue %></li>
        <li><%= event.status %></li>
    </ul>
    <%= link_to "Edit event", edit_event_path(event) %>
    <%= link_to "Invite", new_event_event_attending_path(event) %>
    <%= button_to "Delete Event",  event, method: :delete, data: { turbo_confirm: "Are you sure you want to delete this event"} %>
<% end %>

<h2>Attended Events</h2>
<h3>Past Events</h3>
<% current_user.attended_events.each do |event| %>
    <p><%= event.theme if event.event_date < Time.now %></p>
<% end %>

<h3>Pending Events</h3>
<% current_user.attended_events.each do |event| %>
    <p><%= event.theme if event.event_date > Time.now %></p>
<% end %>